language: c

os:
  - windows
  - linux
  - osx

env:
  - NIMBRANCH=devel ARCH=64

addons:
  apt:
    packages:
      - libssl-dev

before_install:
  - openssl version
  - openssl version -d

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim

script:
  - nimble test

