sudo: false
language: c
os:
  - linux
  - osx
dist: trusty

matrix:
  allow_failures:
    - os: linux

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - git clone --depth 1 https://github.com/nim-lang/nim.git
  - cp csources/bin/nim nim/bin/nim

script:
  - cd nim
  - export PATH=$(pwd)/bin${PATH:+:$PATH}
  - nim c koch
  - ./koch boot -d:release
  #- ./koch testinstall
  - ./koch doc0
  - ./koch csource -d:release
  - ./koch xz -d:release
  - cd ..

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "nim/build/nim-*.tar.xz"
  file_glob: true

  skip_cleanup: true
  on:
    tags: false
